### ISSUE TITLE
Bug: Module Blank Page

### ISSUE THREAD

**Issue by aljawaid** [AXeL-dev/dolibarr-chat-module#1]
I tried chat module on 5.0.4

When trying to go the chat module page from the top menu, I get a blank page.  No error message.  Below is from my dolibarr logs.

`2017-08-06 20:05:48 INFO    92.22.XXX.251   --- Access to /dolibarr/custom/chat/index.php`

`2017-08-06 20:05:48 DEBUG   92.22.XXX.251   sql=SELECT transkey, transvalue FROM llx_overwrite_trans where lang='en_GB'`

`2017-08-06 20:05:48 DEBUG   92.22.XXX.251   Menubase::menuLoad mymainmenu=chat myleftmenu= type_user=0 menu_handler=eldy tabMenu size=0`

`2017-08-06 20:05:48 DEBUG   92.22.XXX.251   sql=SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid`

`2017-08-06 20:05:48 INFO    92.22.XXX.251   --- End access to /dolibarr/custom/chat/index.php`

**Comment by AXeL-dev** [comment]
hum, i have tested it on a fresh 5.0.4 dolibarr & everything seems to work fine, so, before going so far, i just want to ask you about how do you install the module in your dolibarr? did you just put the chat folder in your dolibarr htdocs folder or something else? & after that did you activate the module from the module settings before trying it?
if it's so , please send me a screenshot so i can see what you mean exactly with a blank page, & i want some informations about database tables too, so if you can check on your phpmyadmin if the tables llx_chat, llx_chat_msg_attachment... have been successfully created or not

**Comment by aljawaid** [comment]
self hosted dolibarr on vps centos7 with php7.0 and php 5.6

Uploaded to /custom folder. Enabled module. Icon came up in top menu.  click on it and get a blank white page.

both tables are created in phpmyadmin

**Comment by AXeL-dev** [comment]
Edit: okay, wait, i just saw that you put the module in /dolibarr/custom folder, & i think it will not work there, so just move it in /dolibarr folder & it should work. (between, i will try to fix that, but i remember that i was having troubles with the custom folder for some reasons..)

**Comment by aljawaid** [comment]
ooooh now it works... impressive...

**Comment by AXeL-dev** [comment]
cool, glade to hear that x), i just saw the source of this bug in code & i will try to fix it as fast as possible
