### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by aljawaid** [AXeL-dev/dolibarr-chat-module#2]
Does it have to refresh the full page on each chat message sent?

Is it a group chat and also private (I see private message)?

Does it save messages and show counter on icon/popup when user next logs in?

Can it be switched to a popup so we can carry on working within dolibarr?

Instead of top menu for icon, it should be on top of left menu, or have the option to switch

:)

**Comment by AXeL-dev** [comment]
for the 1st question: no it's work with ajax, & the chat will be refreshed automatically (every 5 seconds by default, but you can change that on module settings)

2 - group chat feature is not yet implemented, but you can send private message by clicking on the message icon on the top right of the user name.

3 - messages are saved yes, on database. the counter feature is not yet implemented (sorry.. i code it just for fan from 1 - 2 years ago, but i can add such features i some one need it)

4 - yes, it's possible to switch it to popup & i was thinking about adding this feature but before that i will need to do something about the user box or change the way messages are shown (i don't really know, it seems a bit hard to implement & for that i just haven't code it yet)

5 - Everything is possible, I just need a little encouragement to keep working on it x)

**Comment by aljawaid** [comment]
this is a very good start on the module.  you need to translate the permissions though.

Also, the default refresh is set at 5secs.. but I mean when I type and then 'send' a message the full page refreshes.

**Comment by aljawaid** [comment]
At the moment it could be used as a delayed messaging system between users (as it is blocking the working in dolibarr). But notifications would then be needed.

**Comment by AXeL-dev** [comment]
okay i see, yes your right, but i can change that so the send button may work with ajax too without refreshing the page

**Comment by AXeL-dev** [comment]
it's not realy blocking work x); you can open it in a new tab & keep working on another dolibarr tab, but yes, it will be more comfortable if it work's as a popup, i think i will work on this feature after fixing the custom folder bug

**Comment by aljawaid** [comment]
haha ok but from a business perspective there are enough tabs already open when you're dealing with products and orders lol

**Comment by AXeL-dev** [comment]
yeah i guess xD

**Comment by AXeL-dev** [comment]
so if you want, just open new issue(s) about each feature you want, & i will try work on it

**Comment by aljawaid** [comment]
maybe even rename the module as 'communications' and then have the current delayed message feature as one part and then popup live chat as the second part.  That would really be useful in a working environment.

**Comment by AXeL-dev** [comment]
yép, i think it would be great too

**Comment by aljawaid** [comment]
It's starting to look cool now... would you be willing to create a module for me?

**Comment by AXeL-dev** [comment]
hum, what kind of module?

**Comment by aljawaid** [comment]
If you have an e-mail I can send you the details?

**Comment by AXeL-dev** [comment]
of course, here it is : anass_denna@hotmail.fr

**Comment by aljawaid** [comment]
sent email :)
