### ISSUE TITLE
Add Chat Notifications

### ISSUE THREAD

**Issue by aljawaid** [AXeL-dev/dolibarr-chat-module#4]
Add flashing bar or number of new messages as user settings for when new messages are received.

**Comment by AXeL-dev** [comment]
i just added this feature on chat popup, please test it & give me your feedback.

**Comment by aljawaid** [comment]
When I log in, there is no notification or flashing bar to show that I have unread notifications...that's what I was expecting

**Comment by AXeL-dev** [comment]
yes i know, currently the popup show you the unread messages count only when your connected (because notification system does not really exist/not yet.. maybe i will work on this issue later)
