### ISSUE TITLE
Allow to Change Chat Bar Colour

### ISSUE THREAD

**Issue by aljawaid** [AXeL-dev/dolibarr-chat-module#5]
Allow (user settings) to change the chat bar default colour and the flashing colour (if notifications are implemented)

Suggestion: Default bar colour = green, new chat message flashing colour = red

**Comment by AXeL-dev** [comment]
soon !

**Comment by AXeL-dev** [comment]
added in version 2.0.0

**Comment by aljawaid** [comment]
excellent, will try it shortly.  I'm sending you email in 5 minutes, please check :)

**Comment by AXeL-dev** [comment]
okay, i will check that after getting some food x) (hungry ><)
